bkrv/bkrv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bkrv/main/urls.py
from django.urls import path, include
from . import views


app_name = 'main'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('users/', include('django.contrib.auth.urls')),
    path('users/register/', views.register, name='register'),
    path('search/', views.ResultListView.as_view(), name='search'),
    path('search/more', views.generate_search_results, name='more'),
    path('post/', views.post, name='post'),
    path('detail/<int:pk>/', views.ReviewDetailView.as_view(), name='detail'),
    path('detail/<int:review_id>/vote', views.vote, name='vote'),
    path('detail/<int:review_id>/comment', views.comment, name='comment'),
]

bkrv/main/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
import datetime
from PIL import Image
import os


class Restaurant(models.Model):
    name = models.CharField(max_length=100)
    time_open = models.TimeField()
    time_close = models.TimeField()
    address = models.CharField(max_length=100)
    type_choices = [
        ('Cafe - Dessert', 'Cafe - Dessert'),
        ('Restaurant', 'Restaurant'),
        ('Bar - Pub', 'Bar - Pub'),
        ('Snack', 'Snack'),
    ]
    type = models.CharField(choices=type_choices, max_length=30)

    def __str__(self):
        return self.name

    @property
    def min_price(self):
        _min = 10000000
        for item in self.restaurantitem_set.all():
            if item.price < _min:
                _min = item.price
        return format(_min, ',').replace(',', '.')

    @property
    def max_price(self):
        _max = 0
        for item in self.restaurantitem_set.all():
            if item.price > _max:
                _max = item.price
        return format(_max, ',').replace(',', '.')

    @property
    def is_open(self):
        return self.time_open <= datetime.datetime.now().time() < self.time_close


def profile_picture_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/users/<username>/<filename>
    return 'users/{}/{}'.format(instance.username, filename)


class CustomUser(AbstractUser):
    picture = models.ImageField(upload_to=profile_picture_path, default='users/default_avatar.jpg')

    def __str__(self):
        return self.username

    @property
    def number_of_reviews(self):
        return self.review_set.count()

    @property
    def number_of_upvotes(self):
        return sum(self.review_set.values_list('upvotes', flat=True))

    @property
    def number_of_downvotes(self):
        return sum(self.review_set.values_list('downvotes', flat=True))


class Review(models.Model):
    review = models.TextField()
    rating = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(10)])
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    @property
    def first_image(self):
        return self.reviewimage_set.first()

    @property
    def number_of_comments(self):
        return self.reviewcomment_set.count()


def review_image_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/reviews/<review_id>/<filename>
    return 'reviews/{}/{}'.format(instance.review.id, filename)


class ReviewImage(models.Model):
    image = models.ImageField(upload_to=review_image_path)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super().save()
        image = Image.open(self.image.path)
        image.thumbnail((768, 768))
        image_path = os.path.splitext(self.image.path)[0] + '-768' + os.path.splitext(self.image.path)[1]
        image.save(image_path)
        image = Image.open(self.image.path)
        image.thumbnail((384, 384))
        image_path = os.path.splitext(self.image.path)[0] + '-384' + os.path.splitext(self.image.path)[1]
        image.save(image_path)

    @property
    def photo768(self):
        return os.path.splitext(self.image.url)[0] + '-768' + os.path.splitext(self.image.url)[1]

    @property
    def photo384(self):
        return os.path.splitext(self.image.url)[0] + '-384' + os.path.splitext(self.image.url)[1]


class RestaurantItem(models.Model):
    name = models.CharField(max_length=50)
    price = models.FloatField()
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ReviewComment(models.Model):
    summary = models.TextField()
    comment = models.TextField()
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)


class Vote(models.Model):
    vote_choices = [
        ('UP', 'Upvote'),
        ('DW', 'Downvote'),
    ]
    vote = models.CharField(choices=vote_choices, max_length=5)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

    def __str__(self):
        return self.vote

bkrv/main/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Review, Restaurant, RestaurantItem, ReviewImage, ReviewComment, Vote
from django.forms import ModelForm


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = CustomUser
        fields = ('username', 'email')


class ReviewForm(ModelForm):

    class Meta:
        model = Review
        fields = ('review', 'rating')


class RestaurantForm(ModelForm):

    class Meta:
        model = Restaurant
        fields = ('name', 'address', 'time_open', 'time_close', 'type')


class RestaurantItemForm(ModelForm):

    class Meta:
        model = RestaurantItem
        fields = ('name', 'price')


class ReviewImageForm(ModelForm):

    class Meta:
        model = ReviewImage
        fields = ('image', )


class VotingForm(ModelForm):

    class Meta:
        model = Vote
        fields = ('vote', )


class CommentForm(ModelForm):

    class Meta:
        model = ReviewComment
        fields = ('summary', 'comment')

bkrv/main/views.py
from .forms import CustomUserCreationForm, RestaurantItemForm, RestaurantForm, ReviewForm, ReviewImageForm, VotingForm, CommentForm
from .models import Review, Vote
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.views.generic.list import ListView
from django.views.generic import DetailView
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import ensure_csrf_cookie
from django.contrib.auth.decorators import login_required
from .modelsAI.ModelController import ModelController
from .utils import get_price_range


class IndexView(ListView):

    context_object_name = 'recent_list'
    template_name = 'main/index.html'

    def get_queryset(self):
        return Review.objects.select_related('restaurant').prefetch_related('reviewimage_set').order_by('-id')[:3]

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['popular_list'] = Review.objects.select_related('restaurant').prefetch_related('reviewimage_set').\
            order_by('-upvotes')[:3]
        return context


save_query = None


class ResultListView(ListView):

    context_object_name = "result_list"
    template_name = 'main/listing.html'

    def get_queryset(self):
        global save_query
        # request sent from search bar
        base_query = Review.objects.select_related('restaurant').\
            prefetch_related('restaurant__restaurantitem_set').all()
        if 'keyword' in self.request.GET:  # query contains 'keyword'
            if self.request.GET.get('keyword'):  # keyword has a value
                query1 = base_query.\
                    filter(restaurant__restaurantitem__name__icontains=self.request.GET.get('keyword')).distinct()
                query2 = base_query.filter(restaurant__name__icontains=self.request.GET.get('keyword')).distinct()
                query3 = base_query.filter(restaurant__address__icontains=self.request.GET.get('keyword')).distinct()
                combined_query = query1 | query2 | query3
                save_query = combined_query
                return combined_query[:3]
            else:  # keyword doesnt have a value
                save_query = base_query
                return base_query[:3]

        # request sent from search filter
        elif 'sd[]' in self.request.GET or 'sp[]' in self.request.GET or 'sc[]' in self.request.GET:
            # type-based query
            if self.request.GET.getlist('sc[]'):
                query2 = base_query.filter(restaurant__type__in=self.request.GET.getlist('sc[]')).distinct()
            else:  # no 'sc' is passed
                query2 = base_query.distinct()
            # price-based query
            if self.request.GET.getlist('sp[]'):
                stack_query = Review.objects.none()
                for params in self.request.GET.getlist('sp[]'):
                    price_range = get_price_range(params)
                    query = base_query.filter\
                        (restaurant__restaurantitem__price__range=(price_range['low'], price_range['high'])).distinct()
                    stack_query = stack_query | query
                query3 = stack_query
            else:  # no 'sp' is passed
                query3 = base_query.distinct()
            combined_query = query2 & query3
            save_query = combined_query
            return combined_query[:3]

        # request sent from search filter with no item selected / invalid request
        else:
            save_query = base_query
            return base_query[:3]


def generate_search_results(request):

    if 'offset' in request.GET:
        offset = int(request.GET.get('offset'))
        results = save_query[offset:offset+3]
        result_list = list()
        for result in results:
            data = {'id': result.id, 'image_url': result.first_image.image.url, 'rating': result.rating,
                    'name': result.restaurant.name, 'type': result.restaurant.type,
                    'address': result.restaurant.address,
                    'min': result.restaurant.min_price, 'max': result.restaurant.max_price,
                    'time_open': result.restaurant.time_open, 'time_close': result.restaurant.time_close,
                    'is_open': result.restaurant.is_open, 'upvotes': result.upvotes,
                    'comments': result.number_of_comments}
            result_list.append(data)

        return JsonResponse({'error': False, 'results': result_list})

    return JsonResponse({'error': True})


class ReviewDetailView(DetailView):

    template_name = 'main/detail.html'
    queryset = Review.objects.select_related('restaurant').select_related('user').\
        prefetch_related('reviewcomment_set').prefetch_related('restaurant__restaurantitem_set')

    @method_decorator(ensure_csrf_cookie)
    def dispatch(self, *args, **kwargs):
        return super(ReviewDetailView, self).dispatch(*args, **kwargs)


@login_required
def vote(request, review_id):

    review = get_object_or_404(Review, id=review_id)
    if request.POST.get('reqType') == 'vote':
        vote_type = request.POST.get('voteType')
        vote_form = VotingForm({'vote': vote_type})
        if vote_form.is_valid():
            # if user's already voted, update current record
            if Vote.objects.filter(user=request.user, review=review):
                last_state = Vote.objects.filter(user=request.user, review=review).first().vote
                Vote.objects.filter(user=request.user, review=review).update(vote=vote_type)
                # update upvotes/downvotes field
                if last_state == vote_type:  # if last vote == current vote
                    pass
                else:
                    if last_state == 'UP':
                        review.upvotes -= 1
                        review.downvotes += 1
                    else:
                        review.downvotes -= 1
                        review.upvotes += 1
                    review.save()

            # else create new object and save it to database
            else:
                vote_object = vote_form.save(commit=False)
                vote_object.user = request.user
                vote_object.review = review
                vote_object.save()
                # update upvotes/downvotes field
                if vote_type == 'UP':
                    review.upvotes += 1
                else:
                    review.downvotes += 1
                review.save()

            # return current upvotes/downvotes
            return JsonResponse({'error': False, 'upvotes': review.upvotes, 'downvotes': review.downvotes})

    return JsonResponse({'error': True})


@login_required
def comment(request, review_id):

    review = get_object_or_404(Review, id=review_id)
    if request.POST.get('reqType') == 'comment':
        actual_comment = request.POST.get('comment')
        summary = request.POST.get('summary')
        comment_form = CommentForm({'summary': summary, 'comment': actual_comment})
        if comment_form.is_valid():
            comment_object = comment_form.save(commit=False)
            comment_object.review = review
            comment_object.user = request.user
            comment_object.save()
            return JsonResponse({'error': False, 'summary': summary, 'comment': actual_comment})

    return JsonResponse({'error': True})


def register(request):

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('main:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'main/register.html', {'form': form})


@login_required
def post(request):

    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        restaurant_form = RestaurantForm(request.POST)
        # spam filter
        review_text = request.POST.get('review')
        model = ModelController.load_model()
        processor = ModelController.load_preprocessor()
        text = processor.transform_vectorize([review_text])
        if model.predict(text)[0] == 1:  # if review is classified as spam
            return render(request, 'main/post.html',
                          {'review_form': review_form, 'restaurant_form': restaurant_form, 'review_error': True})
        # items handling
        item_name = request.POST.getlist('item_name[]')
        item_price = request.POST.getlist('item_price[]')
        item_form = [RestaurantItemForm({'name': item_name[i], 'price': item_price[i]}) for i in range(0, len(item_name))]
        if not all([form.is_valid() for form in item_form]):
            return render(request, 'main/post.html',
                          {'review_form': review_form, 'restaurant_form': restaurant_form, 'item_error': True})
        # images handling
        images = request.FILES.getlist('file[]')
        image_form = [ReviewImageForm(None, {'image': images[i]}) for i in range(0, len(images))]
        if not images:
            return render(request, 'main/post.html',
                          {'review_form': review_form, 'restaurant_form': restaurant_form, 'image_error': True})
        if review_form.is_valid() and restaurant_form.is_valid() \
                and all([form.is_valid() for form in item_form]) \
                and all([form.is_valid() for form in image_form]):
            # store restaurant to database
            restaurant = restaurant_form.save()
            # store review to database
            review = review_form.save(commit=False)
            review.user = request.user

bkrv/main/templates/main/post.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<!-- Custom Fonts -->
		<link rel="stylesheet" href="{% static 'main/custom-font/fonts.css' %}" />
		<!-- Bootstrap -->
		<link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}" />
		<!-- Font Awesome -->
		<link rel="stylesheet" href="{% static 'main/css/font-awesome.min.css' %}" />
		<!-- Bootsnav -->
		<link rel="stylesheet" href="{% static 'main/css/bootsnav.css' %}">
		<!-- Custom stylesheet -->
		<link rel="stylesheet" href="{% static 'main/css/listing-detail.css' %}" />
		<link rel="stylesheet" href="{% static 'main/css/post.css' %}"/>
		<!-- AngularJS -->
		<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
        <!-- Simple line Icon -->
	    <link rel="stylesheet" href="{% static 'main/css/simple-line-icons.css' %}">
	    <!-- Themify Icon -->
	    <link rel="stylesheet" href="{% static 'main/css/themify-icons.css' %}">
		<!-- Swipper Slider -->
		<link rel="stylesheet" href="{% static 'main/css/swiper.min.css' %}">
	</head>
	<body>

		<!-- Preloader -->

		<div id="loading">
			<div id="loading-center">
				<div id="loading-center-absolute">
					<div class="object"></div>
					<div class="object"></div>
					<div class="object"></div>
					<div class="object"></div>
					<div class="object"></div>
					<div class="object"></div>
					<div class="object"></div>
					<div class="object"></div>
					<div class="object"></div>
					<div class="object"></div>
				</div>
			</div>
		</div>

		<!--End off Preloader -->

		<!-- Header -->
		<header>
			<!-- Navbar -->
			<nav class="navbar bootsnav">
				<div class="container">
					<!-- Header Navigation -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
							<i class="fa fa-bars"></i>
						</button>
					</div>
					<!-- Navigation -->
					<div class="collapse navbar-collapse" id="navbar-menu">
                        <ul class="nav navbar-nav menu">
							<li><a href="{% url 'main:index' %}">Home</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="#">{{ user.username }}</a></li>
                            <li><a href="{% url 'main:logout' %}">Logout</a></li>
                            {% else %}
							<li><a href="{% url 'main:login' %}">Login</a></li>
							<li><a href="{% url 'main:register' %}">Register</a></li>
                            {% endif %}
						</ul>
					</div>
				</div>   
			</nav><!-- Navbar end -->
		</header><!-- Header end -->

		<section id="home" class="home">
			<!-- Carousel -->
			<div id="carousel" class="carousel slide" data-ride="carousel">
				<!-- Carousel-inner -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<img src="{% static 'main/images/listing-food.jpg' %}">
						<div class="overlay">
						</div>
					</div>        
				</div><!-- Carousel-inner end -->
			</div><!-- Carousel end-->
		</section>

		<!--============================= DESCRIPTION =============================-->
		<section class="store-block">
			<div class="container">
				<div class="row">
						<h5 style="margin-bottom: 4px">Write a review</h5>
						<p class="store-description" style="display: block;">
							<span class="store-description-type">Share your favorite place!</span>
						</p>
				</div>
			</div>
		</section>
		<!--//END DESCRIPTION -->
		
		<!--============================= REVIEW DETAILS =============================-->
		<section class="light-bg review-details_wrap">
			<div class="container">
				<div class="review-checkbox_wrap" style="height: auto;">
					<form method="post" enctype="multipart/form-data" action="{% url 'main:post' %}" ng-app="mealApp" ng-controller="mealController">
                        {% csrf_token %}
						<div class="review-checkbox" name="basic_info" >
							<span class="ti-check-box"></span>
							<h6 style="display: inline-block;">Basic information</h6>
							<hr>
						</div>
						<div class="info-content">
                            {% for field in restaurant_form %}
                                <div class="info-input">
                                    <div class="item-label">{{ field.label }}</div>
                                    <div class="item-detail">
                                        {{ field }}
                                    </div>
                                    {% for error in field.errors %}
                                        <small style="color: red">{{ error }}</small>
                                    {% endfor %}
                                </div>
                            {% endfor %}
						</div>

						<div class="review-checkbox" name="detailed_info" style="margin-top: 50px">
							<span class="ti-check-box"></span>
							<h6 style="display: inline-block;">Detail information</h6>
							<hr>
						</div>
						<script>
							var Mapp = angular.module('mealApp', []);
							Mapp.controller('mealController', function($scope) {
								$scope.Meals = [{
									Id: 1
									}];
								$scope.id = 2;
								$scope.addElement = function() {
									$scope.Meals.push({
										Id: $scope.id
									});
									$scope.id = $scope.id + 1;
								};
								$scope.removeElement = function () {
                                    if($scope.id > 2) {
                                        $scope.Meals.pop();
                                        $scope.id = $scope.id - 1;
                                    }
                                };
							});
						</script>
						<div class="info-content">
                            <div ng-repeat="meal in Meals">
                                <div class="info-input">
                                    <div class="item-label">Popular dish</div>
                                    <div class="item-detail">
                                        <input type="text" name="item_name[]" required/>
                                    </div>
                                </div>
                                <div class="info-input">
                                    <div class="item-label">Price</div>
                                    <div class="item-detail">
                                        <input type="text" name="item_price[]" required/>
                                    </div>
                                </div>
                            </div>
                            {% if item_error %}
                            <small style="color: red">Please enter a valid number</small>
                            {% endif %}
							<div class="add-meal-btn" style="margin-bottom: 10px">
								<button type="button" ng-click="addElement()">+</button>
							</div>
                            <div class="add-meal-btn" style="margin-bottom: 10px">
								<button type="button" ng-click="removeElement()">-</button>
							</div>
						</div>
						<div class="info-content">
                            <div class="info-input">
                                <div class="item-label" style="width: 100%">{{ review_form.review.label }}</div>
                                {{ review_form.review|add_class:"custom_textarea" }}
                                {% if review_error %}
                                <small style="color: red">Please do not spam</small>
                                {% endif %}
                            </div>
                            <div class="info-input">
                                <div class="item-label">{{ review_form.rating.label }}</div>
                                <div class="item-detail">
                                    {{ review_form.rating|attr:"min:0"|attr:"max:10" }}
                                </div>
                            </div>
						</div>
						<div class="info-content">
							<div class="info-input">
								<div class="item-label" style="width: 100%">Images</div>
								<div id="wrapper" style="margin-top: 30px">
                                    <div class="add-meal-btn" style="margin-bottom: 10px">
                                        <label for="upload_file">+</label>
                                        <input type="file" style="display: none" id="upload_file" name="file[]" onchange="preview_image()" multiple/>
                                    </div>
								</div>
							</div>
                            {% if image_error %}
                            <small style="color: red">Please choose an image</small>
                            {% endif %}
                            <div id="image_preview"></div>
						</div>
						<input class="btn submit_btn" type="submit" value="Upload" style="margin-top: 30px">
					</form>
				</div>
			</div>
		</section>
		<!--//END REVIEW DETAILS -->

		<!-- Footer -->
		<footer>
			<!-- Footer top -->
			<div class="container footer_top">
				<div class="row">
					<div class="col-lg-4 col-sm-7">
						<div class="footer_item">
							<h4>About</h4>
							<img class="logo" src="{% static 'main/images/logo.png' %}" style="width: 200px; height: 50px" />
							<p>This website serves no other purposes than education.<br>The source code for the project can be found at<br>
                                https://github.com/vuduc153/Restaurants-Review-Django
                            </p>
							<ul class="list-inline footer_social_icon">
								<li><a href=""><span class="fa fa-facebook"></span></a></li>
								<li><a href=""><span class="fa fa-twitter"></span></a></li>
								<li><a href=""><span class="fa fa-youtube"></span></a></li>
								<li><a href=""><span class="fa fa-google-plus"></span></a></li>
								<li><a href=""><span class="fa fa-linkedin"></span></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div><!-- Footer top end -->

			<!-- Footer bottom -->
			<div class="footer_bottom text-center">
				<p class="wow fadeInRight">
					Made with
					<i class="fa fa-heart"></i>
					by
					<a target="_blank" href="http://bootstrapthemes.co">Bootstrap Themes</a>
					2016. All Rights Reserved
				</p>
			</div><!-- Footer bottom end -->
		</footer><!-- Footer end -->

		<!-- JavaScript -->
		<script>
		function preview_image() 
		{
		 var total_file=document.getElementById("upload_file").files.length;
		 for(var i=0;i<total_file;i++)
		 {
		  $('#image_preview').append("<img src='"+URL.createObjectURL(event.target.files[i])+"'><br>");
		 }
		}
		</script>
		<!-- JavaScript -->
		<script src="{% static 'main/js/jquery-1.12.1.min.js' %}"></script>
		<script src="{% static 'main/js/bootstrap.min.js' %}"></script>


		<!-- JS Implementing Plugins -->
		<script src="{% static 'main/js/isotope.js' %}"></script>
		<script src="{% static 'main/js/isotope-active.js' %}"></script>

		<script src="{% static 'main/js/jquery.scrollUp.min.js' %}"></script>

		<script src="{% static 'main/js/main.js' %}"></script>
	</body>	
</html>	

bkrv/main/templates/main/register.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en" >

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
	<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300'>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto:400,700,300'>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="{% static 'main/css/login-register.css' %}">
	
</head>

<body>
	<!-- Preloader -->
	<div id="loading">
		<div id="loading-center">
			<div id="loading-center-absolute">
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
				<div class="object"></div>
			</div>
		</div>
	</div>
	<!--End off Preloader -->
	<div class="signup__container">
	<div class="container__child signup__thumbnail">
	</div>
	<div class="container__child signup__form">
		<form method="post">
             {% csrf_token %}
             {% for field in form %}
             <div class="form-group" style="margin-bottom: 10px">
				<label>{{ field.label_tag }}</label>
				{{ field|add_class:"form-control" }}
                 {% for error in field.errors %}
                    <small style="color: red">{{ error }}</small>
                 {% endfor %}
             </div>
             {% endfor %}
			<div class="m-t-lg">
				<ul class="list-inline">
					<li>
						<input class="btn btn--form" type="submit" name="submit" id="submit" value="Sign up" />
					</li>
					<li>
						<a class="signup__link" href="{% url 'main:login' %}">Already a member?</a>
					</li>
				</ul>
			</div>
		</form>  
	</div>
</div>
    <!-- JavaScript -->
    <script src="{% static 'main/js/jquery-1.12.1.min.js' %}"></script>
    <script src="{% static 'main/js/main.js' %}"></script>
</body>

</html>